from bs4 import BeautifulSoup

async def fetch(url: str, use_proxy: bool, verbose: bool, **kwargs: int) -> BeautifulSoup | None: ...
async def fetch_many(urls: list[str],use_proxy: bool,verbose: bool,workers: int,**kwargs: int,) -> list[BeautifulSoup | None]: ...