def validate_url(url: str) -> None: ...
def validate_proxy_param(proxy_param: bool) -> None: ...
def validate_kwargs(**kwargs: int) -> None: ...
def get_sleeping_time(**kwargs: int) -> int: ...
def validate_params(url: str, use_proxy: bool, **kwargs: int) -> int: ...